version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - ./db_data:/var/lib/postgresql/data
    env_file: ../.env.local
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.10
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    env_file: ../.env.local
volumes:
  db_data:
